name: CI

on: [push, pull_request]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: [ubuntu-latest]
    steps:
      - name: step 1
        run: echo ${{ secrets.HOST }}
      - uses: actions/checkout@v1
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }} 
          password: ${{ secrets.PASSWORD }} 
          port: 22
          script: whoami 
        
